name = "Client Pack"
author = "Aurelianvs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c78113848abcc1607c6a8f767a4ee021f4349c6fa4f375f8b8ae2ed1dfc5546"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
