name = "Client Pack"
author = "Aurelianvs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13291874f19453c0d54cd6e87499f9bdf39cf87315a6eef9acdaf5052a264918"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
