name = "Client Pack"
author = "Aurelianvs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa42e90e121fb034071800b8d40cf716a52bdc8fb5b289833c1bc869c0604ef"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
