name = "Client Pack"
author = "Aurelianvs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "136af8770fc194a4af76b69fd0e403f4f48ac076da840c8dd5cab077744c09d4"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
